### ISSUE TITLE
Equality operators

### ISSUE THREAD

**Issue by tindzk** [outr/scalarelational#17]
``ColumnLike`` defines the following operators:

```scala
def ===(value: T) = DirectCondition(this, Operator.Equal, value)
def <>(value: T) = DirectCondition(this, Operator.NotEqual, value)
def !=(value: T) = DirectCondition(this, Operator.NotEqual, value)
```

Is there a reason for using ``===`` instead of ``==``? By analogy, I'd expect that ``!==`` would be used for inequality. Can we get rid of the redundant ``NotEqual`` operator ``<>``?

**Comment by darkfrog26** [comment]
You can't override == functionality in Scala. This is the reason that other DSLs like Slick do the same thing.

**Comment by darkfrog26** [comment]
I would be okay with getting rid of <> except that it's actually common among SQL in certain use-cases.

**Comment by tindzk** [comment]
How about using ``!==`` instead of ``!=`` for consistency?

**Comment by darkfrog26** [comment]
I'm not opposed to that...perhaps we could support both?

**Comment by qbert65536** [comment]
Either way please keep <> , it's ugly I agree but it's common place for SQL.

On Mon, Jul 6, 2015 at 10:11 AM, Matt Hicks <notifications@github.com>
wrote:

> I'm not opposed to that...perhaps we could support both?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/outr/scalarelational/issues/17#issuecomment-118885859>
> .
>



-- 
Thanks!
Charlie
512-698-2009

**Comment by darkfrog26** [comment]
So should we remove != or just add !==?

**Comment by tindzk** [comment]
FYI, I removed ``!=`` and added ``!==``.
