### ISSUE TITLE
Type-safe references

### ISSUE THREAD

**Issue by tindzk** [outr/scalarelational#18]
When writing queries, it happened to me a few times that I was comparing two unrelated key columns. Can we have type-safe references instead of Integers for foreign keys? An example:

```scala
val supplierId = column[Ref[Supplier]]("supplierId", new ForeignKey(Supplier.id))
```

I tried to implement this feature, but couldn't find a viable solution because table specifications are ``object``s and therefore cannot be used as a type argument. Obviously, we could just rely on the ``case class`` that the mapper would use, but I'd like this feature to be part of ``core/``.

**Comment by darkfrog26** [comment]
I like the idea but I'll have to think about the best way to support this.

**Comment by darkfrog26** [comment]
What if we were to find a way to make Column[Table, Type] so that all columns would be unique and type-safe?

**Comment by tindzk** [comment]
I like it. Would this mean that the mapper becomes part of the ``core`` sub-project?

Slick lets the developer specify the table using a tuple, but this notation is inconvenient and hard to read:

```scala
class Suppliers(tag: Tag) extends Table[(Int, String, String)](tag, "suppliers") {
  def id = column[Int]("id", O.PrimaryKey)
  def name = column[String]("name")
  def street = column[String]("street")
  def * = (id, name, street)
}
```

**Comment by darkfrog26** [comment]
I've actually tried to accomplish this before, but Scala's lack of good self-typing kept me from making much progress.
