### ISSUE TITLE
Improve grammar of DSL

### ISSUE THREAD

**Issue by tindzk** [outr/scalarelational#21]
This should lead to a syntax error:

```scala
val query = (
  select (rating.avg)
  from coffees
    and id > Some(1)
)
```

**Comment by darkfrog26** [comment]
I'm not sure I follow...why should this lead to a syntax error?

**Comment by tindzk** [comment]
Because ``and`` may only appear after ``where``, unless I'm wrong.

**Comment by darkfrog26** [comment]
Ah, I missed that when I was reading the snippet.  The only way we can do that is to follow a DSL approach the way JOOQ does where instead of a case class that has all the DSL methods you have several classes that build to the query class.

**Comment by darkfrog26** [comment]
I'm not sure this necessarily belongs in 1.1.  Unless you are willing to take on the task in the near future to handle it, I think this should be a further out objective.

**Comment by tindzk** [comment]
Well, it's clearly a bug. I don't like shipping software with bugs that we are aware of.

**Comment by lukaseder** [comment]
You may as well never ship, then ;) Cheers

**Comment by darkfrog26** [comment]
It's not exactly a bug, just a less restrictive DSL.  I definitely would like to resolve this at some point, but it doesn't break anything, it just allows you to use grammar that isn't allowed in SQL.

**Comment by tindzk** [comment]
I agree that it is not top priority, but the above code throws a non-meaningful runtime exception which took me some time to figure out.

**Comment by darkfrog26** [comment]
it throws a runtime exception?  It shouldn't...`and` is a synonym for `where` in the DSL currently.

**Comment by darkfrog26** [comment]
Oh right...it's not a synonym anymore...I see the problem.

**Comment by darkfrog26** [comment]
This shouldn't be incredibly difficult to fix, but very time consuming.  Let's tackle this in 1.2.

**Comment by darkfrog26** [comment]
Is it acceptable to you that `and` and `or` work as aliases to `where` if there is no existing `where` clause?

**Comment by darkfrog26** [comment]
This has been updated. Please evaluate the current state of the code and open a new ticket if you have some suggested changes.
