### ISSUE TITLE
Changing column size of Array[Byte]

### ISSUE THREAD

**Issue by tindzk** [outr/scalarelational#22]
``Array[Byte]`` corresponds to a ``BINARY`` column of the size 1024. In certain situations it is necessary to specify a different size. I'm using the following workaround:

```scala
object Page extends Table("Page")(ds) {
  implicit def myByteArray = new DataType[Array[Byte]] {
    def sqlType(column: ColumnLike[_]) = "BINARY(102400)" // defaults to 1024
    def toSQLType(column: ColumnLike[_], value: Array[Byte]) = value
    def fromSQLType(column: ColumnLike[_], value: Any) = value.asInstanceOf[Array[Byte]]
  }

  // ...
  val content = column[Array[Byte]]("content")(myByteArray, implicitly[Manifest[Array[Byte]]])
}

**Comment by darkfrog26** [comment]
We could add a ColumnProperty "ColumnLength" that could be used for all variable length column definitions (VARCHAR, NVARCHAR, BINARY, BLOB, etc.) and if the property isn't defined it would just default to Datastore.BinaryDefaultLength or something?

**Comment by darkfrog26** [comment]
...the default in Datastore would give the ability to override the default for your entire Datastore if desired.

**Comment by tindzk** [comment]
Sounds good to me.

**Comment by darkfrog26** [comment]
@tindzk, do you want to give it a go or would you like me to?

**Comment by tindzk** [comment]
I can do it, but let me first finish the two pending pull requests.

**Comment by tindzk** [comment]
I just had a look at ``DataType``:

```scala
val VarcharType = s"VARCHAR(${Int.MaxValue})"
val VarcharIngoreCaseType = s"VARCHAR_IGNORECASE(${Int.MaxValue})"
```

Do you think it's a good idea to have these defaults? Depending on the SQL implementation, we may waste a lot of space. According to [this article](https://www.simple-talk.com/sql/database-administration/whats-the-point-of-using-varchar%28n%29-anymore/) it can also negatively impact the performance.

**Comment by tindzk** [comment]
Implemented in my [``column-length`` branch](https://github.com/tindzk/scalarelational/tree/column-length). I can submit a pull request after #16 has been merged.

**Comment by qbert65536** [comment]
I noticed that also, and I would agree that defaulting to the max is
unwise.  I did this in my own ORM and it came back to bite me.

On Tue, Jul 7, 2015 at 4:02 PM, Tim Nieradzik <notifications@github.com>
wrote:

> I just had a look at DataType:
>
> val VarcharType = s"VARCHAR(${Int.MaxValue})"val VarcharIngoreCaseType = s"VARCHAR_IGNORECASE(${Int.MaxValue})"
>
> Do you think it's a good idea to have these defaults? Depending on the SQL
> implementation, we may waste a lot of space. According to this article
> <https://www.simple-talk.com/sql/database-administration/whats-the-point-of-using-varchar%28n%29-anymore/>
> it can also negatively impact the performance.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/outr/scalarelational/issues/22#issuecomment-119339677>
> .
>



-- 
Thanks!
Charlie
512-698-2009

**Comment by darkfrog26** [comment]
You're correct. This is a hold-over from H2-specific code since H2 only uses the actual length of the String supplied up to the max so there is no performance penalty for that.  I agree it should be changed in other SQL implementations.

**Comment by darkfrog26** [comment]
This is resolved now, right?

**Comment by tindzk** [comment]
Yes, I'll close this issue.

**Comment by tindzk** [comment]
But we should still think about changing the default size for strings.

**Comment by darkfrog26** [comment]
Except that in H2 MaxValue is ideal.

**Comment by tindzk** [comment]
Should there be driver-dependent default sizes?

**Comment by darkfrog26** [comment]
Hmmm...perhaps or we could just set it to a good middle-ground...what did you have in mind for a default?

**Comment by tindzk** [comment]
I would go for 65535 which is the [maximum row size](http://stackoverflow.com/questions/7755629/varchar255-vs-tinytext-tinyblob-and-varchar65535-vs-blob-text) in some databases. Furthermore, we could provide the data types ``TinyText``, ``Text``, ``MediumText`` and ``LongText`` if the developer expects longer strings.

**Comment by darkfrog26** [comment]
I'm fine with 65535.  For the other datatypes you mean light-weight wrappers around String?  This raises an issue we should probably discuss further.  In outrquery's ORM there was a SQL type and the ORM type. This was very useful for mapping arbitrary types to standard SQL types.  More and more I'm wondering if perhaps this would still be useful so you could have "LongText" be the SQL type but "String" be the Scala representation and the DataType provides the conversion.  This is not much different than what we're currently doing.

**Comment by tindzk** [comment]
I agree, but we actually don't need to change the current architecture to introduce ``MediumText`` etc. We only have to define a type similar to ``StringDataType`` and not make it implicit. Then, the developer can explicitly refer to it:

```scala
val text = column[String]("text", LongTextDataType)
```

**Comment by hraban** [comment]
I think the consensus for postgresql is still that "TEXT" type is better than VARCHAR(N) for any type of text, even small. E.g. http://blog.jonanin.com/2013/11/20/postgresql-char-varchar/ :

> Use TEXT instead of VARCHAR or CHAR; TEXT has exactly the same performance
> and space usage characteristics while being much more flexible.

**Comment by darkfrog26** [comment]
@hraban, if you'd be interested in creating the postgresql sub-project for ScalaRelational it would probably be very straight-forward.  Especially if you are very familiar with PostgreSQL

**Comment by qbert65536** [comment]
I was going to try to tackle this too, @hraban let me know if you end up
not doing it .

On Sun, Jul 19, 2015 at 11:32 AM, Matt Hicks <notifications@github.com>
wrote:

> @hraban <https://github.com/hraban>, if you'd be interested in creating
> the postgresql sub-project for ScalaRelational it would probably be very
> straight-forward. Especially if you are very familiar with PostgreSQL
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/outr/scalarelational/issues/22#issuecomment-122678791>
> .
>



-- 
Thanks!
Charlie
512-698-2009

**Comment by darkfrog26** [comment]
@qbert65536, I would recommend taking another look at the MySQL implementation you did. Try removing "@Ignore" from the "TableSpec" test and running it.

**Comment by qbert65536** [comment]
Ok I'll fix the tests.

On Sun, Jul 19, 2015 at 8:25 PM, Matt Hicks <notifications@github.com>
wrote:

> @qbert65536 <https://github.com/qbert65536>, I would recommend taking
> another look at the MySQL implementation you did. Try removing "@Ignore
> <https://github.com/Ignore>" from the "TableSpec" test and running it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/outr/scalarelational/issues/22#issuecomment-122726607>
> .
>



-- 
Thanks!
Charlie
512-698-2009
