### ISSUE TITLE
Auto-generate query methods

### ISSUE THREAD

**Issue by tindzk** [outr/scalarelational#23]
For each table I'm manually defining the following two functions:

```scala
def query(qry: Query[Vector[SelectExpression[_]], QueryResult[_]]): EnhancedIterator[Page] =
  qry.to[Page].result.converted

def byId(id: Int): Option[Page] =
  ds.session {
    query(Page.q where Page.id === Some(id))
      .headOption
  }
```

How about providing a mixin ``MapTo[MappedType]`` in the mapper with these methods? We could even add a function for arbitrary columns: ``by[T](column: ColumnLike[T], value: T): Option[MappedType]``

**Comment by darkfrog26** [comment]
I'm not sure I really understand what you're getting at here...

**Comment by darkfrog26** [comment]
I see. I would be okay with this addition.
