### ISSUE TITLE
`updating` handler

### ISSUE THREAD

**Issue by tindzk** [outr/scalarelational#24]
The ``updating`` handler seems to ignore the returned ``Update`` object. See https://github.com/tindzk/scalarelational/commit/242f42668195a4e66daff7a16eb2eff1617c9c36 for a failing test.

**Comment by darkfrog26** [comment]
See my response on that commit.  I think your spec is buggy. :-p

**Comment by tindzk** [comment]
I submitted a pull request that makes the handlers slightly more flexible.

Another thing I would like to discuss is ``persist`` as in:

```scala
User.persist(user).result
```

Should it return the ``user`` object with those fields updated which where changed by the ``updating`` handler? This is not the case right now. I believe it would be better to return ``Unit``.

**Comment by darkfrog26** [comment]
Persist in Mapper returns an updated instance of the case class with the id field set.  This is incredibly useful when you are doing things like persisting one class and need the id to set on another persist.

**Comment by tindzk** [comment]
We could just return the ID as an Integer.

**Comment by darkfrog26** [comment]
We could, but doing it this way allows you to abstract further because you can then pass it to a controller that takes the case class and it expects to use the ID. What's the issue with returning the instance?

**Comment by tindzk** [comment]
As mentioned above, it doesn't update those fields that were changed by ``updating``.

**Comment by darkfrog26** [comment]
Ah, right....sorry, I'm having a hard time concentrating with so much noise around me. :)

What would you prefer?  Should it update the class with anything that was changed during updating, or should it just return the id?

**Comment by tindzk** [comment]
I would prefer to just return the ID which is also more in line with other frameworks.

**Comment by darkfrog26** [comment]
I would be fine with that change.
