### ISSUE TITLE
Merging `Column` and `ColumnLike`

### ISSUE THREAD

**Issue by tindzk** [outr/scalarelational#27]
For https://github.com/outr/scalarelational/pull/25 I had to change certain interfaces to take ``ColumnLike`` instead of ``Column`` and also move a few methods around. How about merging ``Column`` and ``ColumnLike``?

**Comment by darkfrog26** [comment]
We can't do that because there are SQL functions and other things that are like columns but are not columns.  I was thinking about changing the name to 'Field' instead of 'ColumnLike', but I'm afraid that's going to cause even more issues because of the namespace collisions.

**Comment by tindzk** [comment]
I agree, but there should be a better distinction between those two types. Right now, it is not immediately obvious when to take ``ColumnLike`` or ``Column`` as a function argument.

**Comment by darkfrog26** [comment]
If you have any suggestions on how to make that naming better I'm definitely open to suggestions.  Do you like '''Field''' as a base or something else?

**Comment by darkfrog26** [comment]
Going ahead and closing this based on our conversation. If you still think there is something to be done here please re-open the ticket.
