### ISSUE TITLE
PostgreSQL Support

### ISSUE THREAD

**Issue by darkfrog26** [outr/scalarelational#36]
We need explicit support for PostgreSQL and an implementation of AbstractTableSpec to validate that it works.

**Comment by Kiwi** [comment]
"verify the create table DDL is correct" in {
      val sql = testDatastore.ddl(List(test)).toVector
      sql.size should equal(1)
      sql.head.sql should equal("CREATE TABLE IF NOT EXISTS test_table(id INTEGER AUTO_INCREMENT, name VARCHAR(1024) NOT NULL UNIQUE, date TIMESTAMP, PRIMARY KEY(id));")
    }

This test will fail on postgresql. AUTO_INCREMENT doesn't exist there. The right way to write that query would be as such:

CREATE TABLE IF NOT EXISTS test_table(id SERIAL, name VARCHAR(1024) NOT NULL UNIQUE, date TIMESTAMP, PRIMARY KEY(id));

**Comment by darkfrog26** [comment]
You can resolve this by overriding columnPropertiesSQL in BasicDDLSupport (mixed into SQLDatastore)

**Comment by darkfrog26** [comment]
For now you can just presume Int and add a TODO to fix it and I'll get a look at it after the tests work.

**Comment by darkfrog26** [comment]
I've created a new PR (https://github.com/outr/scalarelational/pull/54) that should help you provide much better customization to finish this ticket. I'll post another comment once it has been merged.
