### ISSUE TITLE
Instruction refactoring

### ISSUE THREAD

**Issue by tindzk** [outr/scalarelational#37]
We should stick to the convention of using parentheses to denote side-effects. I would suggest the following style changes:

```scala
User(name).insert: Instruction[Int]

User(name).insert(): Int
Future(User(name).insert()): Future[Int]

// as opposed to:

User(name).insert.result: Int
User(name).insert().async: Future[Int]
```

**Comment by darkfrog26** [comment]
So you propose removing all of the async references from ScalaRelational?

**Comment by darkfrog26** [comment]
Oh, and the code you proposed: ```Future(User(name).insert()): Future[Int]``` won't work because it won't be in a ```Session```.

**Comment by tindzk** [comment]
Ok. I was thinking about improving the session handling too. My code is scattered with ``ds.session { ... }`` blocks which I would like to get rid of. Can we pass the session using an implicit instead? Conceptually it is not too different from Scala's ``ExecutionContext``.

**Comment by darkfrog26** [comment]
I was actually thinking about adding support for "auto sessions" that would go well with "sticky sessions".  It would offer you the ability to just ignore the concept of sessions entirely and if there isn't already a session for that thread then it would create it.  The problem with passing around a reference to a session to other threads is it complicates knowing when that session can be terminated and the connection returned to the pool.

**Comment by darkfrog26** [comment]
Another problem of sharing sessions as your implicit concept suggests is that though Connection (the primary point of a Session is to wrap around a JDBC Connection) may be thread-safe, each thread should have its own Connection to perform optimally.

I added a convenience ```apply()``` method to ```Instruction``` to allow structuring as you suggested but did not remove "async" as it is still extremely valid in my opinion.

I'm closing this issue. If you have additional suggestions to provide to make this better feel free to re-open.
