### ISSUE TITLE
Use macros for Query.to and Query.asCase

### ISSUE THREAD

**Issue by tindzk** [outr/scalarelational#48]
As of now, ``Query.to`` and ``Query.asCase`` use reflection. The performance could be greatly improved with macros.

**Comment by darkfrog26** [comment]
Though it could be improved, I don't think the improvement is all that drastic.  As you can see from the current benchmarks, the performance is pretty good.  That is not to say I'm opposed to this, I think this is a necessary thing, I just want it clear that the performance gains are less substantial than the benefits of just getting rid of reflection.

**Comment by darkfrog26** [comment]
`Query.to` support has been added. We need to decide in 1.2 whether we should switch entirely to the Macro version. With regards to `Query.asCase` in the current representation there is no possible way to support it in a Macro.
