### ISSUE TITLE
Improve Table

### ISSUE THREAD

**Issue by tindzk** [outr/scalarelational#49]
There are several improvements to be made in ``Table``:

* Rethink ``tableName``; it is not obvious that ``name`` may be ``null``
* Don't take a ``Manifest`` in ``column``
* Remove ``addColumn``
* ``columns`` should be immutable and the columns may be detected using a macro
* ``primaryKey`` must be a correctly typed ``Column``
* ``allFields`` and ``fieldName`` use reflection and should be removed

**Comment by darkfrog26** [comment]
Are you meaning we should start using TypeTag instead of Manifest or get rid of it entirely?  It's currently used to determine if a Column is Option.

**Comment by darkfrog26** [comment]
Regarding `addColumn` how should a `Table` know about the `Column`s associated with it?

**Comment by darkfrog26** [comment]
Using Macros we might be able to clean up a lot of this. I'll look into it further.

**Comment by darkfrog26** [comment]
Updated `Table` and `Column`. This is the best I can do until we incorporate some Macros to remove some of the internal junk. Moving to 1.3 to tackle that.

**Comment by darkfrog26** [comment]
This is all dealt with in this new code.
