### ISSUE TITLE
Create macros to generate Table class definitions from case classe.

### ISSUE THREAD

**Issue by Jacoby6000** [outr/scalarelational#5]
It would be nice to have a way to _not_ write the table class definitions, which in many cases wind up being a mirror of a case class.  If I understand correctly, this is one of the large gripes with slick (I know it is for me)... A large benefit to this, is that when you change a case class, you don't have to change the table definition (and vice versa).  

For example, this code
```scala
case class Supplier(id: Int, name: String, street: String, city: String, state: String, zip: String)
 
object ExampleDatastore extends H2Datastore(mode = H2Memory("example"), columnNameAdapter = SnakeUpperCaseAdapter) {
  object suppliers extends Table("SUPPLIERS", classOf[Supplier])
}
```

Would expand to 

```scala
case class Supplier(id: Int, name: String, street: String, city: String, state: String, zip: String)
 
object ExampleDatastore extends H2Datastore(mode = H2Memory("example"), columnNameAdapter = SnakeUpperCaseAdapter) {
  object suppliers extends Table("SUPPLIERS") {
    val id = column[Int]("ID", PrimaryKey)
    val name = column[String]("NAME")
    val street = column[String]("STREET")
    val city = column[String]("CITY")
    val state = column[String]("STATE")
    val zip = column[String]("ZIP")
  }
}
```

Note:  A columnNameAdapter was added to the ExampleDatastore adapter, and a classOf[T] was added to the suppliers object definition.

Eventually, special cases should be supported, where you can override the default implementation.

Using the example above, a person could write

```scala
case class Supplier(id: Int, name: String, street: String, city: String, state: String, zip: String)
 
object ExampleDatastore extends H2Datastore(mode = H2Memory("example"), columnNameAdapter = SnakeUpperCaseAdapter) {
  object suppliers extends Table("SUPPLIERS", classOf[Supplier]) {
    val id = column[Int]("SUP_ID", PrimaryKey)
    val name = column[String]("SUP_NAME")
  }
}
```

Doing this, the "id" and "name" field would have their own custom implementations, and the macro implementation would not be used. This second feature will probably need more flexibility than my example provides, but the idea is there.

**Comment by darkfrog26** [comment]
This is 99% complete with the only lacking feature of including the original body of the object.
https://github.com/outr/scalarelational/blob/master/core/src/main/scala/org/scalarelational/extra/typedTable.scala#L39
That currently just includes all "vals", but I can't seem to figure out how to include the entire body. You'd think ```..$template``` would work, but it gives a compile error if I try.

@Jacoby6000, if you wouldn't mind taking a look at this and giving some feedback I'd appreciate it.
