### ISSUE TITLE
Return value of `insertInto()`

### ISSUE THREAD

**Issue by tindzk** [outr/scalarelational#56]
Example:

```scala
session {
  insertInto(suppliers, 150, "The High Ground", "100 Coffee Lane",
    "Meadows", "CA", "93966").result                                       
}                                                                          
```

This returns -1, but it would make more sense to return the ID of the inserted row, i.e. 150.

**Comment by darkfrog26** [comment]
This is technically not a bug at all. This currently follows the JDBC paradigm for returning generated keys. Though I'm not opposed to adding a layer of abstraction on top of this to always provide the primary key back, this would require massive refactoring to make it happens and really is a much larger issue than this.
