### ISSUE TITLE
Support for non-integer primary keys

### ISSUE THREAD

**Issue by tindzk** [outr/scalarelational#63]
Internally, [we assume](https://github.com/outr/scalarelational/blob/master/core/src/main/scala/org/scalarelational/model/SQLDatastore.scala#L109) that the primary key is set on an Integer column. This limitation causes problems with PostgreSQL when the specified primary key is not an Integer column.

**Comment by darkfrog26** [comment]
This is a larger problem than described. We must support tables without primary keys as well.

**Comment by tindzk** [comment]
What do you think about introducing a parameterised trait for the primary key (``with PrimaryKey[String]``)?

**Comment by darkfrog26** [comment]
On `Column`?

**Comment by darkfrog26** [comment]
Pushing this to 2.0

**Comment by darkfrog26** [comment]
The simplification of the core model makes this a non-issue as any Column can be a primary key.
