### ISSUE TITLE
Table DSL: Derive `createColumn` from existing column

### ISSUE THREAD

**Issue by tindzk** [outr/scalarelational#64]
After adding a column to an existing table, I'm using ScalaRelational's versioning support to upgrade the database.

It would be useful, if the correct parameters could be derived from an existing column such as:
 `Comment.parentId.createColumn.result`

As opposed to:

```scala
createColumn[Option[Int], Int](Comment.tableName, "parentId",  new ForeignKey(Comment.id))
  .foreach(_.execute(Datastore))
```

**Comment by darkfrog26** [comment]
you mean like this? https://github.com/outr/scalarelational/blob/master/core/src/main/scala/org/scalarelational/dsl/DDLDSLSupport.scala#L18

**Comment by tindzk** [comment]
Thanks.

**Comment by darkfrog26** [comment]
Note that functionality has been in the code for months.
