### ISSUE TITLE
Use implicit session context

### ISSUE THREAD

**Issue by tindzk** [outr/scalarelational#71]
One downside of the `session` block is that it doesn't get enforced during compile-time. I would suggest to make `result` take the session context as an implicit.

**Comment by tindzk** [comment]
`session` could be changed to pass the session context as its first argument:

```scala
def session[T](f: SessionContext => T): T

session { implicit s =>
  ...
}
````

**Comment by darkfrog26** [comment]
As discussed, we can do the following:

```scala
withSession { implicit session =>
  ...
}
```

I think we should use `withSession` to make its purpose more clear and avoid namespace collision for the variable name `session`.
