### ISSUE TITLE
Decouple Table from Datastore

### ISSUE THREAD

**Issue by tindzk** [outr/scalarelational#74]
`Table` has a dependency on `Datastore`. We should consider removing `Table.datastore`, so that the same table could be potentially used in multiple data stores.

Furthermore, we should keep a list of tables in `Datastore.tables: List[Table]`, so that `Datastore.exists()` can be removed and rewritten as `Datastore.tables.contains()`.

**Comment by darkfrog26** [comment]
How is the `Datastore` going to know the tables associated with it then?

**Comment by tindzk** [comment]
As per your suggestion we could reference the tables when instantiating the datastore:

```scala
object MyDatastore extends Datastore {
  val table1 = table[Table1]
  val table2 = table[Table2]
}
```

**Comment by darkfrog26** [comment]
What about something along these lines:

```scala
object ModelDataStore extends DataStore {
  val suppliers = table[Suppliers]
  val coffees = table[Coffees]
}

trait Suppliers extends Table {
  val id = column[Option[Int]](columnName("supId"), primaryKey, autoIncrement)
  val name = column[String](unique)
  val street = column[String]
  val city = column[String]
  val state = column[String]
  val zip = column[String]
}

trait Coffees extends Table {
  val id = column[Option[Int]](columnName("cofId"), primaryKey, autoIncrement)
  val name = column[String](unique)
  val supFk = column[Int](foreignKey[Suppliers])
  val price = column[Double]
  val sales = column[Int]
  val total = column[Int]
}
```

This would offer a more concise representation of the database while remaining highly descriptive and all of the "extras" (`*`, validations, implementations, etc.) would be generated via Macros.  If a column name is not supplied it will use the field name during Macro expansion.

Thoughts?

**Comment by tindzk** [comment]
Looks good. What would be the type of `suppliers` and `coffees`? It could be something like `Suppliers with TableExtensions`. `TableExtensions` is just a trait that defines `*` and other query features. The macro would expand to:

```scala
val suppliers = new Suppliers with TableExtensions {
  def * = ...
}
```

**Comment by tindzk** [comment]
I would suggest to capitalise the column properties. In which scope are they defined?

**Comment by darkfrog26** [comment]
why do you need `TableExtensions`?  If `Table` is a trait it can define the abstract methods for everything it should include and it would just be:

```scala
val suppliers: Suppliers = table[Suppliers]
```

**Comment by darkfrog26** [comment]
I originally had them capitalized, but switched to lower-case since I defined them as methods inside the `Table` trait.

**Comment by tindzk** [comment]
Indeed, `TableExtensions` is not really needed. It makes sense to define those methods in `Table`.

However, I'd argue that the column properties should not be provided by `Table`, because this will implicitly expose them (`db.tableName.primaryKey`). Column properties should be ideally part of the DSL.

**Comment by darkfrog26** [comment]
okay, so do you think we should continue to include them in another package as objects and classes that are capitalized?

**Comment by tindzk** [comment]
Yes.

**Comment by darkfrog26** [comment]
I'm cool with that.

**Comment by darkfrog26** [comment]
The only problem I'm having with this is being able to generate the `*`.  Certainly I can generate it, but unless it's an external dependency code-completion won't have property access to the type since it would be a Tuple of columns.

**Comment by darkfrog26** [comment]
How about this?

```scala
object ModelDatabase extends Database {
  val suppliers: Suppliers = table[Suppliers]
  val coffees: Coffees = table[Coffees]
}

trait Suppliers extends Table {
  val id: Column[IntType] = column(IntType.primaryKey.autoIncrement.name("supId"))
  val name: Column[VarCharType] = column(VarCharType.unique.ignoreCase)
  val street: Column[VarCharType] = column(VarCharType)
  val city: Column[VarCharType] = column(VarCharType)
  val state: Column[VarCharType] = column(VarCharType)
  val zip: Column[VarCharType] = column(VarCharType)
}

trait Coffees extends Table {
  val id: Column[IntType] = column(IntType.primaryKey.autoIncrement.name("cofId"))
  val name: Column[VarCharType] = column(VarCharType.unique.ignoreCase)
  val supFk: Column[IntType] = column(IntType.foreignKey[Suppliers])
  val price: Column[DecimalType] = column(DecimalType)
  val sales: Column[IntType] = column(IntType)
  val total: Column[IntType] = column(IntType)
}
```

**Comment by darkfrog26** [comment]
Table would remain a trait so that `table[Suppliers]` can generate `def primaryKeys: Seq[Column[_]]` and other generated information.

**Comment by darkfrog26** [comment]
This is fully implemented and now that `Table` is defined as a trait and has no reference to the `Database` directly, it can be re-used if desired in multiple databases.
