### ISSUE TITLE
Shorten README.md

### ISSUE THREAD

**Issue by tindzk** [outr/scalarelational#75]
We shouldn't duplicate the entire manual in `README.md`. We can shorten the file to the abstract, and instead link to the website and the manual.

**Comment by darkfrog26** [comment]
As soon as ScalaRelational.org is updated to properly reference both the manual and the scaladocs we can trim the README to a minimal representation.

**Comment by tindzk** [comment]
How should ScalaRelational.org look like?

**Comment by darkfrog26** [comment]
either reference the manual directly, or provide a simple intro with links to github, the manual, and the scaladocs

**Comment by qbert65536** [comment]
I could get a few simple sites together if you guys want to vote on three to see which you like best ?  I'd also like to get a better looking / reading tutorial going

**Comment by darkfrog26** [comment]
@qbert65536 that would be great. We have a new manual we're trying to integrate, it's just not really visible yet: http://scalarelational.org/scalarelational/latest/index.html

**Comment by qbert65536** [comment]
Ok will do.  I'm also moving my existing code base to scalarelational using MySQL so I might have something to contribute coming up.
