### ISSUE TITLE
Question:  Re: id

### ISSUE THREAD

**Issue by kenphused** [outr/scalarelational#78]
I have created a table using a varchar field (email) as my primary key.  When creating a mapping via MappedTable, it is mandatory to create a field named 'id' of type Option[Int] (trait Entity -> trait Id).  I explicitly do **NOT** want to use the field 'id'.  What is the workaround for solving this issue?

-Ken

**Comment by darkfrog26** [comment]
Can you give me some more details as to how it is mandatory?  The name `id` should not be mandatory, but it does currently require you have a `Int` id field at the moment (although this is an open ticket we're working to address).  You can create a primary key `Int` and then set `email` as `Unique`.  Would that solve your problem?

**Comment by darkfrog26** [comment]
Closing this for lack of response. If you have not been able to get this to work please re-open the ticket.
