### ISSUE TITLE
Change createColumn's return type

### ISSUE THREAD

**Issue by tindzk** [outr/scalarelational#91]
`create` (for tables) returns `Int` whereas `createColumn` returns `List[CallableInstruction]`. To perform the change, the user has to call `foreach(_.execute(Datastore))`. I would suggest to use a more consistent return type.

**Comment by darkfrog26** [comment]
Agreed, this has already been resolved in 2.0.0: https://github.com/outr/scalarelational/blob/2.0.0/model/src/main/scala/org/scalarelational/DatabaseDDLSupport.scala#L17

Do you think it's worthwhile I fix in 1.x or is it sufficient that this is dealt with in 2.0.0?

**Comment by tindzk** [comment]
No, it's not urgent for me. I will just have to be careful when using `createColumn` because I tend to forget the `foreach` function call.

**Comment by darkfrog26** [comment]
then I'm going to go ahead and close this issue.
