### ISSUE TITLE
Array[Byte] values get zero-padded in MariaDB

### ISSUE THREAD

**Issue by tindzk** [outr/scalarelational#94]
A quick workaround would be to encode the actual length in the first element.

There is also a `VARBINARY` type which anologous to `VARCHAR`: http://dev.mysql.com/doc/refman/5.7/en/binary-varbinary.html

**Comment by darkfrog26** [comment]
As  discussed, this can be resolved by using `BLOB` instead. This should be handled much better in 2.0, but this is one the reasons we have to migrate to database-specific functionality in 2.0 is to handle scenarios like this better.

**Comment by tindzk** [comment]
This may be used as a temporary workaround:

```scala
// Update table
CallableInstruction(
  "ALTER TABLE `tableName` MODIFY `columnName` BLOB NOT NULL"
).execute(Datastore)

// Use custom datatype for Array[Byte] columns
implicit def arrayBlob = new DataType[Array[Byte], Array[Byte]](
  Types.BLOB,
  SQLType("BLOB"),
  new SQLConversion[Array[Byte], Array[Byte]] {
     override def toSQL(column: ColumnLike[Array[Byte], Array[Byte]], value: Array[Byte]): Array[Byte] = value
    override def fromSQL(column: ColumnLike[Array[Byte], Array[Byte]], value: Array[Byte]): Array[Byte] = value
  })
```
